/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./Raidexi/**/*.{js,ts,jsx,tsx}",
    "./features/**/*.{js,ts,jsx,tsx}",
    "./Shared/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--signal-blue)",
        "primary-light": "var(--signal-blue-soft)",
        "primary-dark": "var(--signal-blue-dark)",
        accent: "var(--tailor-red)",
        "accent-light": "var(--tailor-red-soft)",
        brass: "var(--brass)",
        sage: "var(--sage)",
        "background-light": "var(--surface-canvas)",
        "background-dark": "var(--ink)",
        "surface-white": "var(--surface-paper)",
        "surface-light": "var(--surface-linen)",
        "surface-hover": "var(--surface-hover)",
        "surface-dark": "var(--ink)",
        "surface-card": "var(--surface-paper)",
        "panel-bg": "var(--surface-paper)",
        "panel-header": "var(--surface-linen)",
        "input-bg": "var(--surface-linen)",
        "text-main": "var(--ink)",
        "text-secondary": "var(--ink-soft)",
        "text-muted": "var(--ink-muted)",
        "text-dim": "var(--ink-faint)",
        "text-dark": "var(--ink)",
        "border-subtle": "var(--hairline)",
        "border-color": "var(--hairline-strong)",
        "border-dark": "rgba(23, 19, 15, 0.34)",
        "border-highlight": "var(--signal-blue)",
        blue: {
          50: "#f1f6f1",
          100: "#dde7dd",
          200: "#c1d0c3",
          300: "#9caf9f",
          400: "#778f7c",
          500: "#5d7465",
          600: "#4b5f52",
          700: "#384b40",
          800: "#2d3d34",
          900: "#243229",
          950: "#141d18",
        },
        cyan: {
          400: "#c8a16f",
          500: "var(--brass)",
          600: "#7c4f22",
        },
      },
      fontFamily: {
        display: ["Cormorant Garamond", "serif"],
        sans: ["Manrope", "sans-serif"],
        mono: ["IBM Plex Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.6rem",
        md: "0.9rem",
        lg: "1.15rem",
        xl: "1.35rem",
        "2xl": "1.7rem",
        "3xl": "2rem",
        full: "9999px",
      },
      transitionTimingFunction: {
        atelier: "cubic-bezier(0.32, 0.72, 0, 1)",
      },
      animation: {
        "pulse-fast": "pulse 1.6s cubic-bezier(0.32, 0.72, 0, 1) infinite",
        marquee: "marquee 25s linear infinite",
        pulse: "pulse 2.4s cubic-bezier(0.32, 0.72, 0, 1) infinite",
        float: "float 7s cubic-bezier(0.32, 0.72, 0, 1) infinite",
        "float-slow": "float-slow 9s cubic-bezier(0.32, 0.72, 0, 1) infinite",
        shimmer: "shimmer 3s cubic-bezier(0.32, 0.72, 0, 1) infinite",
        orbit: "orbit 22s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        orbit: {
          "0%": { transform: "rotate(0deg) translateX(100px) rotate(0deg)" },
          "100%": { transform: "rotate(360deg) translateX(100px) rotate(-360deg)" },
        },
      },
      boxShadow: {
        glass: "0 24px 80px -52px rgba(24, 23, 20, 0.48), inset 0 1px 0 rgba(255,255,255,0.78)",
        "glass-lg": "0 32px 100px -58px rgba(24, 23, 20, 0.55), inset 0 1px 0 rgba(255,255,255,0.85)",
        "3d": "0 32px 90px -52px rgba(24, 23, 20, 0.52)",
        "glow-blue": "0 0 28px rgba(93, 116, 101, 0.18), 0 0 70px rgba(93, 116, 101, 0.08)",
        "glow-cyan": "0 0 24px rgba(165, 109, 43, 0.16), 0 0 60px rgba(165, 109, 43, 0.08)",
      },
    },
  },
  plugins: [],
};
